version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test # replace with your test command
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build an artifact
          command: npm run build # replace with your build command
      - store_artifacts:
          path: dist/ # replace with your build output directory
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: deploy
          command: ./deploy.sh # replace with your deploy command
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
