version: 2.1
jobs:
  build:
    environment:
      PORT: ${PORT}
      DB_TEST_HOST: ${DB_TEST_HOST}
      SECRET_KEY: ${SECRET_KEY}
      CLOUD_NAME: ${CLOUD_NAME}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
    docker:
      - image: circleci/node:15.14.0
      - image: mongo:4.1.6-xenial
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install project dependencies
          command: npm install --verbose
      - run:
          name: Install TypeScript
          command: npm install --save-dev typescript
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules
      - run:
          name: Compile TypeScript
          command: npx tsc
      - run:
          name: Run tests
          command: npm run test:ci
      - run:
          name: Start the application in dev mode
          command: npm run dev
workflows:
  version: 2.1
  run_build:
    jobs:
      - build
