version: 2.1
jobs:
  build:
    environment:
      NODE_ENV: "test"
    working_directory: ~/guidebook
    docker:
      docker:
        - image: circleci/node:14.17.0
        - image: mongo:4.1.6-xenial
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install project dependencies
          command: npm install --verbose
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm test -- --runInBand
workflows:
  version: 2.1
  run_build:
    jobs:
      - build
